# set shell
set -g default-shell /bin/zsh

setw -g mouse on

# Ativar o true-color
set -g default-terminal "screen-256color"

# Melhorando o modo de cópia no tmux
setw -g mode-keys vi

# Definir a tecla de prefixo como Ctrl + A (opcional, se preferir ao invés de Ctrl + B)
set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

# Divisão de janela vertical (atalho padrão: Ctrl + A seguido de % para split vertical)
bind % split-window -h

# Divisão de janela horizontal (atalho padrão: Ctrl + A seguido de " para split horizontal)
bind '"' split-window -v